name: Advanced Security Settings
description: GHAS settings policy

resource: repository
where:
- |
  repository.name.startsWith("GitOps", StringComparison.InvariantCultureIgnoreCase)
  || repository.name.startsWith("a", StringComparison.InvariantCultureIgnoreCase)

configuration:
    advancedSecurity:
        secretScanning: true
        secretScanningPushProtection: true
